### API SQUARES - EXAMPLE REQUESTS
### ==================================

### Get all squares
GET http://localhost:8000/square

###

### Get square by id
GET http://localhost:8000/square/1

###

### Add square
POST http://localhost:8000/square
Content-Type: application/json

{
  "name": "New square",
  "description": "New square Description",
  "capacity": 2000,
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [
        [
          8.40498,
          49.00951
        ],
        [
          8.40578,
          49.00949
        ],
        [
          8.40578,
          49.00919
        ],
        [
          8.40498,
          49.00919
        ],
        [
          8.40498,
          49.00951
        ]
      ]
    ]
  }
}

###

### Update square by id
PUT http://localhost:8000/square/16
Content-Type: application/json

{
  "name": "New square updated",
  "description": "New square updated Description",
  "capacity": 2500,
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [
        [
          8.40598,
          49.00951
        ],
        [
          8.40678,
          49.00949
        ],
        [
          8.40678,
          49.00919
        ],
        [
          8.40598,
          49.00919
        ],
        [
          8.40598,
          49.00951
        ]
      ]
    ]
  }
}

###

### Add given point to the nearest edge in the square
PUT http://localhost:8000/square/16/add_point
Content-Type: application/json

{
  "point": {
    "type": "Point",
    "coordinates": [
      8.405393,
      49.008940
    ]
  }
}

###

### Get Square Centroid
GET http://localhost:8000/square/1/centroid

###

### Validate if the given point is inside square
GET http://localhost:8000/square/1/contain_point
Content-Type: application/json

{
  "point": {
    "type": "Point",
    "coordinates": [
      8.404335,
      49.009257
    ]
  }
}

###

### Delete square by id
DELETE http://localhost:8000/square/16

###

